### ISSUE TITLE
As a user I want to create a lobby as gamemaster so other people can join it.

### ISSUE THREAD

**Issue by Aece96** [sopra-fs21-group-4/server#2]
# Task List:
Button for lobby creation (changes mode for user entity)
Game master mode for a user entity
Create a link to the created lobby

# Time estimate:
12h

# Reference to userstory:
This task is part of userstory #1.

**Comment by Max-Zurbriggen** [comment]
Commit:
a44eb2e645b331b1a53abefa07782682fa98f69d
