### ISSUE TITLE
create game loop

### ISSUE THREAD

**Issue by Max-Zurbriggen** [sopra-fs21-group-4/server#9]
creating a scheduled recurring loop which iterates over all lobbies to update their states and sends responses to the users with updated information

Time estimate: 4h
User story: sopra-fs21-group-4/client#11

**Comment by Stud-FH** [comment]
implemented but not tested yet

**Comment by Max-Zurbriggen** [comment]
Commit:
a44eb2e645b331b1a53abefa07782682fa98f69d
